### ISSUE TITLE
Omitting `null` values

### ISSUE THREAD

**Issue by bjw-s** [TGNThump/terraform-provider-vyos#1]
Hi!

Thanks so much for creating this fork! One thing I am running in to is that `null` values are being added to the values.

Example (slightly abbreviated) data structure:

```hcl
resource "vyos_config" "service-dhcp-server" {
  path = "service dhcp-server"

  value = jsonencode(
    {
      # main setup
      "hostfile-update" = {} # Create DNS record per client lease, by adding clients to /etc/hosts file. Entry will have format: <shared-network-name>_<hostname>.<domain-name>
      "host-decl-name"  = {} # Will drop <shared-network-name>_ from client DNS record, using only the host declaration name and domain: <hostname>.<domain-name>
      "shared-network-name" = {
        "RESCUE" = {
          "authoritative" = {}
          "ping-check"    = {}
          "subnet" = {
            "192.168.15.0/24" = {
              "domain-name"    = lookup(zone_config.dhcp, "domain_name", null)
              "default-router" = lookup(zone_config.dhcp, "default_router", cidrhost(var.networks[zone], 1))
              "lease"          = "86400"
              "name-server"    = lookup(zone_config.dhcp, "name_server", cidrhost(var.networks[zone], 1))
            }
          }
        }
      }
    }
  )
}
```

(The lookup for `zone_config.dhcp` is referring to a var that is set in a `for_loop`, it defaults to `null` if the variable can't be found)

Results in this error:
```console
module.config.vyos_config.service-dhcp-server: Modifying... [id=service dhcp-server]
╷
│ Error: No
│
│   with module.config.vyos_config.service-dhcp-server,
│   on modules/config/service-dhcp-server.tf line 1, in resource "vyos_config" "service-dhcp-server":
│    1: resource "vyos_config" "service-dhcp-server" {
│
│ shared-network-name RESCUE subnet 192.168.15.0/24 domain-name: invalid type <nil>
```

It would be great if those `null` values would be somehow excluded from the config. Or am I perhaps missing the correct way to "exclude" things?

**Comment by TGNThump** [comment]
I'd need to check if null values are used to represent anything in the vyos json config schema to say if automatically dropping the keys is a good idea, but I can give you a snippit of my vyos_dhcp_server module to show how I've handled this for host_decl_name in my config:

```hcl
variable "host_decl_name" {
  type    = bool
  default = false
}
```

```hcl
resource "vyos_config" "dhcp_server" {
  path = "service dhcp-server"
  value = jsonencode(
    merge(
      var.host_decl_name ? { host-decl-name = {} } : {},
      var.hostfile_update ? { hostfile-update = {} } : {},
      {
        shared-network-name = {
          // ...
        }
      }
    )
  )
}
```

**Comment by TGNThump** [comment]
It would make the interface a lot nicer to use if we could get away with it, and I don't think vyos makes use of nulls anywhere in their json, as they use an empty object for no-value keys.

@andamasov Maybe this is something you could confirm for us?

**Comment by zdc** [comment]
@TGNThump yes, you are right - valueless configuration nodes are internally represented as empty nodes.
Maybe this will be changed at some time to Null.
