### ISSUE TITLE
Save boot config

### ISSUE THREAD

**Issue by ammmze** [TGNThump/terraform-provider-vyos#18]
I'm curious how others are using this and persisting the changes. I don't see an option to "save" the config, which would save it to `/config/config.boot` like the foltik provider had. Are most people using this using some other method to save the boot config?

**Comment by TGNThump** [comment]
… this would explain a few things. Not sure how I missed this.

**Comment by ammmze** [comment]
Awesome! That was quick! Thank you 🎉
